### ISSUE TITLE
[License-Info-Guideline(JP)] feedback　で明らかになった要検討が必要な箇所

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#41]
■OpenChain Japan WG，LicenseInfoSWG　日時  ：2019/10/01(火) 15:00-17:00
議事録より，検討が必要な個所をissue化．

  - [ ]  #22 ライセンスを遵守するのに必要な関係情報の追加
  - [x]  #21 OSSコンプライアンスの言葉が出てくるが、あくまでもライセンス情報を話に絞った方がいい 
  - [x]  #23 サプライチェーン上で・・・の文言について、具体的な優しい文面にした方がいい
  - [x]  #24 リーフレットではOSS情報という文言を使用しているのでリーフレットに合わせた方がいい
  - [ ]  #25  課題があるでは無く、解決策を記載して誘導した方がいい
  - [x]  #26  SPDX Liteの章でいきなりツールの話が出ているが、事前にツールを使用して自動生成出来る話を説明した方がいい
  - [x]  #27  SPDXとSPDX Liteの位置づけの章で、タグの説明が無いので、説明を入れた方がいい
  - [x]  #28  SPDXとSPDX Liteの位置づけの章の改行が無くなっている
  - [x]  #29  Full SpecのSPDXよりもSPDX Liteによる記載の方が・・・、については、SPDX Liteの方がいいとは言えない
  - [x]  #30  2. 必要なライセンス情報の項目については、表に記載されている番号を入れた方が分かりやすい
  - [x]  #31  用語でソフトウェアが使われているが、OSSに統一した方がいいのでは
  - [x]  #32  Files Analyzedの手作業でfalseの記載について、説明を追加した方がいい
  - [x]  #33  Concluded LicenseとDeclared Licenseがほぼ同じ説明になっている
  - [x]  #34  NOASSERTIONの記載は最初に持ってきた方がいい
  - [x]  #35  Copyright Textは著作権者の情報なのか、著作者の情報なのか？
  - [x]  #36  License Identifier 一意になる識別子・・・とは、何の一意なのか説明が入れた方がいい
  - [x]  #37 Package Comment以下の説明が無い
  - [x]  #38  modification record以下がPackage Comment配下に入る事が分かりづらい
  - [x]  #39  3. ライセンス情報の収集方法 この章で何をいいたいのか、1～2行説明を追加する
  - [x]  #40  Concluded Licenseの説明で”又は”では無く、優先度をつけた方がいい
